### ISSUE TITLE
Error on demo page

### ISSUE THREAD

**Issue by amitaibu** [KillerCodeMonkey/stencil-quill#1]
![image](https://user-images.githubusercontent.com/125707/57379186-152d0c00-71af-11e9-89df-a3c1dea3acee.png)

**Comment by KillerCodeMonkey** [comment]
because of a breaking change it is now v2.0.0
styles need to contain the real css-property names in snake-case and not pascal case
so `backgroundColor` needs to be `background-color`

https://killercodemonkey.github.io/stencil-quill/
