### ISSUE TITLE
Invalid Quill container

### ISSUE THREAD

**Issue by madeInLagny** [KillerCodeMonkey/stencil-quill#107]
Hello,
I get the following error
![image](https://user-images.githubusercontent.com/54598963/80568138-ba5f7680-89f6-11ea-823e-94749fc0704a.png)

I imported stencil quill by npm

I import stencil-quill in my component:
`import "../../node_modules/stencil-quill/dist/quill-components.js"`

and quill in index file:
`<link href="https://cdn.quilljs.com/1.3.6/quill.snow.css" rel="stylesheet">
  <script src="https://cdn.quilljs.com/1.3.6/quill.js"></script>
`

I am using a buildless process during development.

Any idea how to fix ?

**Comment by KillerCodeMonkey** [comment]
what do you mean with buildless process?

Did you checked how the `index.html` looks like?

in general there is no `import`-way to use the components in a non stencil project.

just check the readme. simple load stencil-quill components in your index.html after you loaded quill.

https://github.com/KillerCodeMonkey/stencil-quill#using-the-components

**Comment by KillerCodeMonkey** [comment]
https://github.com/KillerCodeMonkey/stencil-quill/blob/master/src/index.html

**Comment by madeInLagny** [comment]
Thanks !

Le mer. 29 avr. 2020 à 09:00, Bengt Weiße <notifications@github.com> a
écrit :

**Comment by KillerCodeMonkey** [comment]
does it work?

**Comment by Bipinpawar** [comment]
Hi @KillerCodeMonkey , I'm getting same error 
![image](https://user-images.githubusercontent.com/47419681/156376519-5e0833f6-2b03-4e61-a8e7-55ff7dc06c37.png)

I have added   <script type="module" src='../node_modules/stencil-quill/dist/quill-components.js'></script>
into my index.html....
