### ISSUE TITLE
How to register own quill module?

### ISSUE THREAD

**Issue by amitaibu** [KillerCodeMonkey/stencil-quill#2]
Thanks for the package! :)

I'd like to register for example a [word count](https://quilljs.com/guides/building-a-custom-module/#counting-words) module (or any other custom one). How can I achieve that with this package? (That is, how do we get access to the quill instance this package is wrapping?)

**Comment by amitaibu** [comment]
Works great!

![image](https://user-images.githubusercontent.com/125707/57386416-f5044980-71bc-11e9-896a-482e7a838646.png)

**Comment by amitaibu** [comment]
Actually my previous comment was wrong. Elm integration works, but the module is not loaded. I get a console error

`quill Cannot import modules/wordcount. Are you sure it was registered?`

I've made sure to `Quill.register('modules/wordcount', wordcount);` before hand. Could it be the stencil-quill has its own Quill version running, and I register it to the wrong quill?

**Comment by KillerCodeMonkey** [comment]
Puh i did not know that for Sure. Maybe IT IS a stencil build Problem, that
it bundles quill?
In general there should ne only one quill object.

Amitai Burstein <notifications@github.com> schrieb am Mi., 8. Mai 2019,
18:36:

**Comment by KillerCodeMonkey** [comment]
strange seems like stencil does not bind initial prop, when passed through the dom?

i tried to set 

```
<quill-component id="quill-component" modules="{ count: true, toolbar: true }" content=""></quill-component>
```

but the modules object is not set in the componentDidMount hook Oo

So how can i pass initial values to a component in stencil ... strange

**Comment by KillerCodeMonkey** [comment]
so mate... i dived down and came up with v3:

all object props are now strings --> JSON.stringified, so i get initial values in plain JS
the component is using the global Quill - object.
i added the wordcount example of quilljs to the demo

**Comment by amitaibu** [comment]
Thanks, I'll check it out!
