### ISSUE TITLE
`https://unpkg.com/stencil-quill@latest/dist/quill-component.js` not accessbile

### ISSUE THREAD

**Issue by amitaibu** [KillerCodeMonkey/stencil-quill#3]
`<script src='https://unpkg.com/stencil-quill@latest/dist/quill-component.js'></script>`

I get 
```
Cannot find "/dist/quill-component.js" in stencil-quill@1.3.0
```

**Comment by KillerCodeMonkey** [comment]
fixed in v2. i was mentally retared *facepalm. thanks for letting me know. should work again

**Comment by amitaibu** [comment]
In fact, also when I use `npm i stencil-quill --save` the JS file is not there, which is probably related.

![image](https://user-images.githubusercontent.com/125707/57382295-59bba600-71b5-11e9-91d6-5ba668bdc2cd.png)

**Comment by DoofisS** [comment]
Seems like this is not working again, also dont you know can I use it in React app for example like 
import 'https://unpkg.com/stencil-quill@latest/dist/quill-components.js' and then just return

<quill-editor content="" format="html" theme="snow"></quill-editor>


for exaple if we are speaking about other web-components i can make it like this:
import "https://1.www.s81c.com/common/carbon/web-components/version/v2.1.1/button.min.js";

<cds-button href="https://www.ibm.com"> Button </cds-button>

and this one will work with React
Thanks, have a good day)

**Comment by DoofisS** [comment]
![image](https://github.com/KillerCodeMonkey/stencil-quill/assets/66424652/4e1b4902-8e5b-42d4-b898-7e67796a4b53)

Now some other errors
If i can provide smth else that can help you pls write)

Anyway thanks for such a fast replay :D
