### ISSUE TITLE
How to get the `quill` instance

### ISSUE THREAD

**Issue by amitaibu** [KillerCodeMonkey/stencil-quill#4]
I'm looking at implementing something similar to the one I described in  https://stackoverflow.com/questions/56048010/how-to-add-blots-under-each-paragraph

That one references a nice [working example](https://codepen.io/alecgibson/pen/EJWEoV).

In that example there's the part `quill.updateContents(new Delta().insert('foo').insert({ label: 'bar' }));`, however I'm not sure how I get the `quill` in the case of stencil-quill

**Comment by KillerCodeMonkey** [comment]
it should be passed in the onEditorCreated method and even when the text changes.

**Comment by amitaibu** [comment]
Right, sorry - I've missed `onEditorCreated`.

**Comment by KillerCodeMonkey** [comment]
no props. so there is a little bit activity in this repo, which is nice :D

**Comment by amitaibu** [comment]
I was able to add alistener to `onInitialised`, but didn't see an `onEditorCreated` being fired.

**Comment by KillerCodeMonkey** [comment]
i do not know how it is done with elm, but in plain javascript you can check my example:
https://killercodemonkey.github.io/stencil-quill/

open dev-tools and check the console.log.

**Comment by amitaibu** [comment]
Indeed, that's what I'm saying :) It's `onInitialised`, but the docs say `onEditorCreated`

**Comment by KillerCodeMonkey** [comment]
ah now i got it.

changed the readme

**Comment by amitaibu** [comment]
So another (related) question. A bit of context: As I'm working through Elm, I create the elm-component through there, and then Elm lets JS know that it was init via a port

```
app.ports.quillEditorCreated.subscribe(function() {
    const quillComponent = document.getElementById('quill-component');

    // How to get `quill` so I could do:
    // quill.updateContents(new Delta().insert('foo').insert({ label: 'bar' }));
});
```

So the specific question is. Can I get the `quill` instance out of `document.getElementById('quill-component');`

**Comment by KillerCodeMonkey** [comment]
i do not know exactly. In my angular component ngx-quill it is a public property and accessable.
So to achieve this with native dom elements i have to define a Prop quill for my component, but this allows to change this property from outside the component, which i do not want.

**Comment by amitaibu** [comment]
Ok, np - I'll try to work around it. I'll write a comment if I get it working :)

**Comment by amitaibu** [comment]
Ok, now my Elm port lets JS know as soon the `<quill-component>` was added to the DOM. So now I can do:

```js
app.ports.quillEditorCreated.subscribe(function() {
    const quillComponent = document.getElementById('quill-component');

    quillComponent.addEventListener('onInitialised', (event) => {
        console.log('onInitialised', event.detail)
        event.detail.updateContents(new Delta().insert('foo').insert({ label: 'bar' }));
    });
});
```

and get my custom Blot:

![image](https://user-images.githubusercontent.com/125707/57467741-c43f1580-728b-11e9-803a-c854f27b8724.png)
