### ISSUE TITLE
Not able to use stencil-quill from npm

### ISSUE THREAD

**Issue by JEricaM** [KillerCodeMonkey/stencil-quill#59]
**Stencil version:** 
```
 "@stencil/core": "^1.8.2"
```
 I'm using the component from cdn and I'm importing in index.html all the files (js, css...) and the component working great, but with npm I'm not able to make it work.

I've installed **stencil-quill** and **quill**, I've included
  `<scrip src="node_modules/stencil-quill/dist/quill-component"></scrip>` 
` <script src="//cdn.quilljs.com/1.3.6/quill.min.js"></script>`
`<link` href="//cdn.quilljs.com/1.3.6/quill.snow.css" rel="stylesheet">`
In my index file...
I should import something else in the project? can you please give more indications?

thank you in advance for the component and your help.

**Comment by KillerCodeMonkey** [comment]
Did You get any Error?

Erica Marchi <notifications@github.com> schrieb am Fr., 17. Jan. 2020,
09:13:

**Comment by KillerCodeMonkey** [comment]
@JEricaM  any updates?

**Comment by JEricaM** [comment]
Hi, sorry for the late response but I'll try today or tomorrow to re-include things and tell you the errors...

**Comment by KillerCodeMonkey** [comment]
closed due to inactivity
